### ISSUE TITLE
projects display broken

### ISSUE THREAD

**Issue by Kennric** [osuosl/climesync#102]
In the current develop branch, some interaction of recently merged features results in the following output for gp (get projects):

```
(h for help) : gp 
(Optional) (y/N) Allow revised?: 
(Optional) (y/N) Allow deleted?: 
(Optional) By project slug: 

users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 


users: 

```

**Comment by subnomo** [comment]
Look like the bug was introduced by https://github.com/osuosl/climesync/commit/f6dbb853bc2f6bc8ef16e22e74623a619dc79213. I'll look into it.

**Comment by Kennric** [comment]
On line 374 of util.py is the block that builds the project list display - there is an error:

```
    for project in response:
        project = OrderedDict()
```

The loop assigns elements to project, then over-writes project with an empty ordered dict. Changing the name of either variable will fix this.

**Comment by subnomo** [comment]
@Kennric I actually just pushed a fix :)

I'll create a PR.
