### ISSUE TITLE
--issue-uri not actually optional

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/climesync#103]
I get the following output when I run this command:
```
$ climesync create-time 0h45m fenestra development 
Invalid arg: --help

status: 400
text: Field issue_uri of time should be string but was sent as null
error: Bad object
```
But `climesync --help` claims that the --issue-uri field is optional. What up with that?

@subnomo @aaroncohen73 

**EDIT** I'd love for somebody else to re-create this issue, I am running into other issues and can't really tell if this was what broke or if it was something else.

**Comment by subnomo** [comment]
I am able to reproduce this, working on a fix.
