### ISSUE TITLE
Feature request: Allow users to retry command

### ISSUE THREAD

**Issue by subnomo** [osuosl/climesync#112]
It'd be helpful if, when a user attempts a command and it fails, climesync would ask if they would like to retry the command. Then climesync could allow them attempt to fill in the input that caused the error (with the other inputs pre-filled).

**Comment by aaroncohen73** [comment]
Instead of trying to parse TimeSync error messages (which would be bug-prone and liable to major revisions each time a new version of the API is released), an alternative solution would be to cache user info, project info, and activity info on login then use that data to validate inputs.
