### ISSUE TITLE
Use Climesync dotfile to store configuration

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/climesync#28]
This file ("~/.climesyncrc" or something like that) would store configuration such as the server URL and authentication information (username and password). Because it would contain password information, read/write access to the file should be restricted to the user who created it.

Information stored in the file would be in the form
```
    TIMESYNC_URL = http://timesync.example.com/v1
```
with the names and values delimited only by an equals sign.

**Comment by ElijahCaine** [comment]
+1

**Comment by aaroncohen73** [comment]
Would this be a substitution for command line arguments or should they be kept in alongside the configuration file?

**Comment by ElijahCaine** [comment]
@aaroncohen73 I agree this should be specified more. The hierarchy I usually see is for priority of values is `commandline args values > .configfile values > hardcoded defaults`. They can all coexist.
