### ISSUE TITLE
Rewrite/Add new unit tests with mocking

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/climesync#31]
Mocking allows more thorough unit tests to be written without adding things to the code to be tested and without unwanted side effects. This should be useful when writing unit tests for the functions that deal with the config file, as we don't want them to actually handle files when running unit tests.

Since `unittest.mock` was introduced in Python 3.3, we would have to use the `mock` package available on PyPi.

**Comment by ElijahCaine** [comment]
+1 on this. Tests should be able to run without depending on an external service.

**Comment by matthewrsj** [comment]
Let me know if you find an elegant way to automate tests on methods that require user input.

**Comment by ElijahCaine** [comment]
@matthewrsj passing a faux argv is how I've seen that done in the past. Python just parses it into a list so you can write your own that matches what a user would input for tests. That would only be used to test your parser function though, not the actual functionality of the project.

**Comment by matthewrsj** [comment]
@ElijahCaine that make sense, thanks.

**Comment by aaroncohen73** [comment]
Superseded by #43
