### ISSUE TITLE
Allow time durations to be submitted/updated/viewed in hh:mm:ss format

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/climesync#32]
Currently Climesync only supports submitting, updating, and viewing times in seconds. For the purpose of usability and user-friendliness, times should be able to be submitted in this format and view_times should always display times in hh:mm:ss format.

**Comment by ElijahCaine** [comment]
iirc the pymesync module supports more human-friendly ways of putting in time (1m, 1h, etc). If not it was at least in development a few months ago.

**Comment by aaroncohen73** [comment]
In that case, Climesync just has to support that format.

**Comment by matthewrsj** [comment]
@aaroncohen73 from the pymesync docs on `create_time()`:

`"duration"` - duration of time spent working on a project. May be entered as a positive integer (which will default to seconds) or a string. As a string duration, follow the format `<val>h<val>m`. An internal method will convert the duration to seconds.

**Comment by aaroncohen73** [comment]
Closed via #36
