### ISSUE TITLE
Support Unicode

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/climesync#34]
Climesync doesn't support unicode characters while the rest of the TimeSync stack does. This should be fixed to include unicode support at every place where Climesync receives user input or makes an API call to Pymesync.

**Comment by ElijahCaine** [comment]
@aaroncohen73 Do you think this would be best done by fully upgrading climesync to Python3 or modifying it to work with unicode on Python2?

**Comment by aaroncohen73** [comment]
@ElijahCaine I would like to upgrade it to Python 3, but Pymesync still uses Python 2.

**Comment by ElijahCaine** [comment]
@aaroncohen73 Do you know if there is anything in pymesync that requires we also be python 2? I'm curious to see what kind of compatibility issues we might run into (if any).

**Comment by aaroncohen73** [comment]
@ElijahCaine On first glance, I don't see anything that would cause major compatibility issues. However, one of the dependencies in Pymesync's `requirements.txt` (wsgiref) doesn't support Python 3. It should be safe to remove, however, because Pymesync doesn't seem to use it.

**Comment by aaroncohen73** [comment]
Closed (finally) via #37
