### ISSUE TITLE
Use docopt for parsing arguments.

### ISSUE THREAD

**Issue by iCHAIT** [osuosl/climesync#38]
I think we should use [docopt](http://docopt.org/) for parsing command line arguments instead of using `argparse`, docopt is a pretty powerful and easy way to parse CLA, plus it is super easy to use.

What do you think?

**Comment by aaroncohen73** [comment]
docopt is a really cool module, but since our current code to parse command line arguments takes up all of 8 lines, I don't think that it's entirely necessary to switch.

**Comment by ElijahCaine** [comment]
@aaroncohen73 If we started doing more command-line argument parsing then something like optparse would be *very* useful.
More command-line options would really help make climesync more usable imo.

**Comment by aaroncohen73** [comment]
@ElijahCaine I see your point. If we used docopt, then allowing commands such as "submit time" and "create user" to be included in scripts as one line commands (i.e. `climesync create user <new user info> -c <baseurl> -u <user> -p <password>`) could be easily implemented.

**Comment by aaroncohen73** [comment]
This has been superseded by #39 for a while now, so I think that it's safe to close the issue
