### ISSUE TITLE
Feature Request: better project user updating

### ISSUE THREAD

**Issue by Kennric** [osuosl/climesync#86]
Updating users for projects is very tedious. The interface does not auto-fill the existing users so that you can easily edit the list - if you want to add someone, you have to remember or find a list of all existing members and enter them as well. Then you must step through every user's role options.

possible solution: have an 'add user to project' function that just takes the slug and a username, then asks for role options. This should display a string of current usernames/roles so you can see who is in the project already.
(Note: this is an issue for activities, slugs, and anything else that takes a comma-delimited list)

Corresponding 'edit project user' and 'delete project user' functions would make it easier to remove and edit roles.

**Comment by aaroncohen73** [comment]
Closed via #88
