### ISSUE TITLE
Feature Request: enhanced data display

### ISSUE THREAD

**Issue by Kennric** [osuosl/climesync#87]
Instead of pages of json directly from TimeSync, it would be nice to see data in a compact table, with just the values I'm interested in. 

For activities and users, a very simple list would be nice, Display name, username, active flag

For projects, I really only need to see name, slugs, and users

For times, I am usually interested in summaries per user and a total. So if I filter on a date range and activity, I want to see:
```
Project X  6/1/2016 - 7/1/2016  Activity: coding
kennric     4h30m 
aacohen     8h20m
total       12h50m
```

or if I don't specify an activity:

```
Project X  6/1/2016 - 7/1/2016
username    coding      testing     research    headdesk
kennric     2h30m       1h10m       0h30m       18h1m
aacohen     8h20m       2h4m        1h45m       1h2m
act. total  12h50m      3h14m       2h15m       19h3m
total       37h12m
```

**Comment by subnomo** [comment]
Closed by #93.
